travis:
  secure:
    BINSTAR_TOKEN: gmeUCow4j5XralQ5J4KQQz07Vtz4OFFtBfOP26XqG55HwkL3xacdu2ed9uV2itVewR/g/GxxtkJX5O5ZIPbdIFm8qulQq2m+q0+tmZKvQRuhmyMCXLxfx4Gl+SfSEXtyCDFZtDHttqiqI3+rMLDRfAezs89MAOfKw7V9PNFGxBVPK1MyG9I4FnK4dQPVzzi3CqRvUKE0h66CeviN4nJjI7rotOG5faMwz5wd5cA/LrmPINUOO8+Vt7sI+afYyMM+FqQt3zdjV+4IOjO9+F3zzq8d0/Q0tyBkyFU38nZ4Ns+fIHyoKj0ZMxmAwhyyJUGk9kEz2XSJcIlNhuiv5aIy6WUgX6fNT9B6aHXPiDR6l/XiO4YhMhjJkjmneEfA5CD9MA8CWOrgwKrTLht0pjg6oxhymvE8/hX4hLGtly9IiwoqTmuWg+Cmb4tydEbrb9IrppDbyPRyY0cqLE3H+Gdtid7OsvPtS72mU8uB9/HeKylbsH0TOTgneXxSLp3uAtiiqZGG0klGHZf4Ewg7gYI27kwm/BP1r0yWTghNhAmfzU3yjPdu1FFu8MUhFA4+LBAVD8rGFhCAOHdoa0/+VKKzwF3wQmCFJpTlUWHrQC4aD/VVfsE9hqpJrqKdXfrCD0pVYRzYPNAlE+spk0RU5TTkhM9064xrIjLp+HAAvpthblI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
